--
-- PostgreSQL database dump
--

\restrict 7zjKCEcRh6eFs3HFuP8LF47UJ9hCuFUq1gzeuqxGxNihZFortfnzdowY8DNod8M

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ingredientes; Type: TABLE; Schema: public; Owner: chefia_user
--

CREATE TABLE public.ingredientes (
    id bigint NOT NULL,
    categoria character varying(255),
    imagen_url character varying(255),
    nombre character varying(255),
    category character varying(255),
    name character varying(255)
);


ALTER TABLE public.ingredientes OWNER TO chefia_user;

--
-- Name: ingredientes_id_seq; Type: SEQUENCE; Schema: public; Owner: chefia_user
--

ALTER TABLE public.ingredientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingredientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ingredientes; Type: TABLE DATA; Schema: public; Owner: chefia_user
--

INSERT INTO public.ingredientes VALUES (1, 'Verduras', '/images/API_image/tomate.png', 'Tomate', NULL, NULL);
INSERT INTO public.ingredientes VALUES (2, 'Verduras', '/images/API_image/cebolla.png', 'Cebolla', NULL, NULL);
INSERT INTO public.ingredientes VALUES (3, 'Verduras', '/images/API_image/ajo.png', 'Ajo', NULL, NULL);
INSERT INTO public.ingredientes VALUES (4, 'Verduras', '/images/API_image/papa.png', 'Papa', NULL, NULL);
INSERT INTO public.ingredientes VALUES (5, 'Verduras', '/images/API_image/zanahoria.png', 'Zanahoria', NULL, NULL);
INSERT INTO public.ingredientes VALUES (6, 'Verduras', '/images/API_image/espinaca.png', 'Espinaca', NULL, NULL);
INSERT INTO public.ingredientes VALUES (7, 'Verduras', '/images/API_image/palta.png', 'Palta', NULL, NULL);
INSERT INTO public.ingredientes VALUES (8, 'Verduras', '/images/API_image/pimiento.png', 'Pimiento', NULL, NULL);
INSERT INTO public.ingredientes VALUES (9, 'Verduras', '/images/API_image/brocoli.png', 'Brócoli', NULL, NULL);
INSERT INTO public.ingredientes VALUES (10, 'Frutas', '/images/API_image/manzana.png', 'Manzana', NULL, NULL);
INSERT INTO public.ingredientes VALUES (11, 'Frutas', '/images/API_image/banana.png', 'Banana', NULL, NULL);
INSERT INTO public.ingredientes VALUES (12, 'Frutas', '/images/API_image/naranja.png', 'Naranja', NULL, NULL);
INSERT INTO public.ingredientes VALUES (13, 'Frutas', '/images/API_image/frutilla.png', 'Frutilla', NULL, NULL);
INSERT INTO public.ingredientes VALUES (14, 'Proteinas', '/images/API_image/pescado.png', 'Pescado', NULL, NULL);
INSERT INTO public.ingredientes VALUES (15, 'Proteinas', '/images/API_image/huevo.png', 'Huevo', NULL, NULL);
INSERT INTO public.ingredientes VALUES (16, 'Proteinas', '/images/API_image/cerdo.png', 'Cerdo', NULL, NULL);
INSERT INTO public.ingredientes VALUES (17, 'Lacteos', '/images/API_image/queso.png', 'Queso', NULL, NULL);
INSERT INTO public.ingredientes VALUES (18, 'Lacteos', '/images/API_image/leche.png', 'Leche', NULL, NULL);
INSERT INTO public.ingredientes VALUES (19, 'Lacteos', '/images/API_image/manteca.png', 'Manteca', NULL, NULL);
INSERT INTO public.ingredientes VALUES (20, 'Lacteos', '/images/API_image/yogur.png', 'Yogur', NULL, NULL);
INSERT INTO public.ingredientes VALUES (21, 'Otros', '/images/API_image/arroz.png', 'Arroz', NULL, NULL);
INSERT INTO public.ingredientes VALUES (22, 'Otros', '/images/API_image/fideos.png', 'Fideos', NULL, NULL);
INSERT INTO public.ingredientes VALUES (23, 'Otros', '/images/API_image/pan.png', 'Pan', NULL, NULL);
INSERT INTO public.ingredientes VALUES (24, 'Otros', '/images/API_image/aceite.png', 'Aceite', NULL, NULL);
INSERT INTO public.ingredientes VALUES (25, 'Otros', '/images/API_image/harina.png', 'Harina', NULL, NULL);
INSERT INTO public.ingredientes VALUES (26, 'Proteinas', '/images/API_image/pollo.png', 'Pollo', NULL, NULL);
INSERT INTO public.ingredientes VALUES (27, 'Proteinas', '/images/API_image/carne.png', 'Carne', NULL, NULL);
INSERT INTO public.ingredientes VALUES (28, 'Verduras', '/images/API_image/zucchini.png', 'Zucchini', NULL, NULL);
INSERT INTO public.ingredientes VALUES (29, 'Verduras', '/images/API_image/berenjena.png', 'Berenjena', NULL, NULL);
INSERT INTO public.ingredientes VALUES (30, 'Verduras', '/images/API_image/pepino.png', 'Pepino', NULL, NULL);
INSERT INTO public.ingredientes VALUES (31, 'Verduras', '/images/API_image/limon.png', 'Limon', NULL, NULL);
INSERT INTO public.ingredientes VALUES (32, 'Otros', '/images/API_image/avena.png', 'Avena', NULL, NULL);
INSERT INTO public.ingredientes VALUES (33, 'Lacteos', '/images/API_image/quesocrema.png', 'Queso crema', NULL, NULL);
INSERT INTO public.ingredientes VALUES (34, 'Legumbres', '/images/API_image/lentejas.png', 'Lentejas', NULL, NULL);
INSERT INTO public.ingredientes VALUES (35, 'Legumbres', '/images/API_image/garbanzos.png', 'Garbanzos', NULL, NULL);
INSERT INTO public.ingredientes VALUES (36, 'Verduras', '/images/API_image/choclo.png', 'Choclo', NULL, NULL);
INSERT INTO public.ingredientes VALUES (37, 'Legumbres', '/images/API_image/arvejas.png', 'Arvejas', NULL, NULL);
INSERT INTO public.ingredientes VALUES (38, 'Legumbres', '/images/API_image/porotos.png', 'Porotos', NULL, NULL);
INSERT INTO public.ingredientes VALUES (39, 'Otros', '/images/API_image/salsadesoja.png', 'Salsa de soja', NULL, NULL);
INSERT INTO public.ingredientes VALUES (40, 'Otros', '/images/API_image/acetobalsamico.png', 'Aceto balsamico', NULL, NULL);
INSERT INTO public.ingredientes VALUES (41, 'Frutas', '/images/API_image/pera.png', 'Pera', NULL, NULL);
INSERT INTO public.ingredientes VALUES (42, 'Frutas', '/images/API_image/durazno.png', 'Durazno', NULL, NULL);



--
-- Name: ingredientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: chefia_user
--

SELECT pg_catalog.setval('public.ingredientes_id_seq', 42, true);


--
-- Name: ingredientes ingredientes_pkey; Type: CONSTRAINT; Schema: public; Owner: chefia_user
--

ALTER TABLE ONLY public.ingredientes
    ADD CONSTRAINT ingredientes_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict 7zjKCEcRh6eFs3HFuP8LF47UJ9hCuFUq1gzeuqxGxNihZFortfnzdowY8DNod8M

